import { Teacher } from './interfaces/teachers-interface';

export const TEACHERS: Teacher[] = [
  {
    id: 1,
    nom: 'Dupont',
    prenom: 'Jean',
    email: '6GJtD@example.com',
    telephone: '0612345678',
    adresse: '12 rue de la paix',
    dateDAjout: new Date(2010, 8, 5),
  },
  {
    id: 2,
    nom: 'Durand',
    prenom: 'Pierre',
    email: 'durandp@example.com',
    telephone: '0612345678',
    adresse: '12 rue de la paix, Cotonou',
    dateDAjout: new Date(2010, 8, 5),
  },
  {
    id: 3,
    nom: 'Martin',
    prenom: 'Paul',
    email: 'mpaulD@example.com',
    telephone: '00229068845678',
    adresse: '13 Rue des alpes',
    dateDAjout: new Date(2010, 8, 5),
  },
  {
    id: 4,
    nom: 'DIARRA',
    prenom: 'Cissé',
    email: 'cissD@example.com',
    telephone: '0033412345678',
    adresse: '15 Fougère Aix Marseille',
    dateDAjout: new Date(2012, 1, 7),
  },
  {
    id: 5,
    nom: 'NKOUKA',
    prenom: 'Ben',
    email: 'ben@yahoo.com',
    telephone: '003956775678',
    adresse: '125 rue Mailon Bruges',
    dateDAjout: new Date(2009, 8, 5),
  },
  {
    id: 6,
    nom: 'Paterson',
    prenom: 'Lois',
    email: 'plois@example.com',
    telephone: '00237042345678',
    adresse: '14 Rue Kolos Douala ',
    dateDAjout: new Date(2013, 8, 5),
  },
];
